# Generated by Django 5.2.5 on 2025-08-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_messages', to='a_rtchat.privatechat'),
        ),
    ]
