# Generated by Django 5.2.5 on 2025-08-19 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0007_alter_message_options_message_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupChat',
        ),
    ]
